[package]
name = "simple_rand"
version = "0.1.0"
authors = ["poyeker <poyeker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_pcg = "0.2.1"
rand_distr = "0.2.2"
itertools = "0.9.0"
